name:                rll
version:             0.1.0.0
github:              "einargs/rll"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rll#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6.2
- text >= 1.2
- mtl >= 2.2
- transformers >= 0.5.6
- prettyprinter >= 1.7.1
- hspec >= 2.9.7

default-extensions:
- BlockArguments
- LambdaCase
- MultiWayIf
- OverloadedStrings
- NamedFieldPuns
- MultiParamTypeClasses
- GeneralizedNewtypeDeriving
- RecordWildCards
- DeriveFunctor
- StandaloneDeriving
- ScopedTypeVariables
- TupleSections
- KindSignatures
- DeriveDataTypeable
- TypeApplications
- StarIsType
- GADTs
- RankNTypes
- EmptyDataDecls
- FlexibleContexts
- TypeFamilies
- DerivingStrategies
- DataKinds
- ConstraintKinds
- TypeOperators
- DeriveGeneric
- DerivingVia

library:
  source-dirs: src

executables:
  rll-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rll

tests:
  rll-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rll
